export const EMPLOYEE_WAIT_LISTS_REQUEST = 'EMPLOYEE_WAIT_LISTS_REQUEST'
export const EMPLOYEE_WAIT_LISTS_SUCCESS = 'EMPLOYEE_WAIT_LISTS_SUCCESS'
export const EMPLOYEE_WAIT_LISTS_FAIL = 'EMPLOYEE_WAIT_LISTS_FAIL'
export const EMPLOYEE_WAIT_LISTS_RESET = 'EMPLOYEE_WAIT_LISTS_RESET'
