export const EVALUATION_MY_LISTS_REQUEST = 'EVALUATION_MY_LISTS_REQUEST'
export const EVALUATION_MY_LISTS_SUCCESS = 'EVALUATION_MY_LISTS_SUCCESS'
export const EVALUATION_MY_LISTS_FAIL = 'EVALUATION_MY_LISTS_FAIL'
export const EVALUATION_MY_LISTS_RESET = 'EVALUATION_MY_LISTS_RESET'

export const EVALUATION_STUDENT_REQUEST = 'EVALUATION_STUDENT_REQUEST'
export const EVALUATION_STUDENT_SUCCESS = 'EVALUATION_STUDENT_SUCCESS'
export const EVALUATION_STUDENT_FAIL = 'EVALUATION_STUDENT_FAIL'
export const EVALUATION_STUDENT_RESET = 'EVALUATION_STUDENT_RESET'

