export const EVALUATION_MY_LISTS_REQUEST = 'EVALUATION_MY_LISTS_REQUEST'
export const EVALUATION_MY_LISTS_SUCCESS = 'EVALUATION_MY_LISTS_SUCCESS'
export const EVALUATION_MY_LISTS_FAIL = 'EVALUATION_MY_LISTS_FAIL'
export const EVALUATION_MY_LISTS_RESET = 'EVALUATION_MY_LISTS_RESET'

