export const ORDER_SUBSCRIPTION_REQUEST = 'ORDER_SUBSCRIPTION_REQUEST'
export const ORDER_SUBSCRIPTION_SUCCESS = 'ORDER_SUBSCRIPTION_SUCCESS'
export const ORDER_SUBSCRIPTION_FAIL = 'ORDER_SUBSCRIPTION_FAIL'
export const ORDER_SUBSCRIPTION_RESET = 'ORDER_SUBSCRIPTION_RESET'
