export const ORDER_SUBSCRIPTION_REQUEST = 'ORDER_SUBSCRIPTION_REQUEST'
export const ORDER_SUBSCRIPTION_SUCCESS = 'ORDER_SUBSCRIPTION_SUCCESS'
export const ORDER_SUBSCRIPTION_FAIL = 'ORDER_SUBSCRIPTION_FAIL'
export const ORDER_SUBSCRIPTION_RESET = 'ORDER_SUBSCRIPTION_RESET'

export const ORDER_SUBSCRIPTION_DATA_SET_REQUEST =
	'ORDER_SUBSCRIPTION_DATA_SET_REQUEST'
export const ORDER_SUBSCRIPTION_DATA_SET_SUCCESS =
	'ORDER_SUBSCRIPTION_DATA_SET_SUCCESS'
export const ORDER_SUBSCRIPTION_DATA_SET_FAIL =
	'ORDER_SUBSCRIPTION_DATA_SET_FAIL'
export const ORDER_SUBSCRIPTION_DATA_SET_RESET =
	'ORDER_SUBSCRIPTION_DATA_SET_RESET'

export const ORDER_LIST_MY_SUBSCRIPTION_REQUEST =
	'ORDER_LIST_MY_SUBSCRIPTION_REQUEST'
export const ORDER_LIST_MY_SUBSCRIPTION_SUCCESS =
	'ORDER_LIST_MY_SUBSCRIPTION_SUCCESS'
export const ORDER_LIST_MY_SUBSCRIPTION_FAIL = 'ORDER_LIST_MY_SUBSCRIPTION_FAIL'
export const ORDER_LIST_MY_SUBSCRIPTION_RESET =
	'ORDER_LIST_MY_SUBSCRIPTION_RESET'

export const ORDER_UNSUBSCRIBE_REQUEST = 'ORDER_UNSUBSCRIBE_REQUEST'
export const ORDER_UNSUBSCRIBE_SUCCESS = 'ORDER_UNSUBSCRIBE_SUCCESS'
export const ORDER_UNSUBSCRIBE_FAIL = 'ORDER_UNSUBSCRIBE_FAIL'
export const ORDER_UNSUBSCRIBE_RESET = 'ORDER_UNSUBSCRIBE_RESET'
