export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_TRIAL_REQUEST = 'USER_TRIAL_REQUEST'
export const USER_TRIAL_SUCCESS = 'USER_TRIAL_SUCCESS'
export const USER_TRIAL_FAIL = 'USER_TRIAL_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_REGISTER_TEACHER_REQUEST = 'USER_REGISTER_TEACHER_REQUEST'
export const USER_REGISTER_TEACHER_SUCCESS = 'USER_REGISTER_TEACHER_SUCCESS'
export const USER_REGISTER_TEACHER_FAIL = 'USER_REGISTER_TEACHER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_TEACHER_DETAILS_REQUEST = 'USER_TEACHER_DETAILS_REQUEST'
export const USER_TEACHER_DETAILS_SUCCESS = 'USER_TEACHER_DETAILS_SUCCESS'
export const USER_TEACHER_DETAILS_FAIL = 'USER_TEACHER_DETAILS_FAIL'
export const USER_TEACHER_DETAILS_RESET = 'USER_TEACHER_DETAILS_RESET'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

// export const USER_LOGOUT = 'USER_LOGOUT'
