export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_TRIAL_REQUEST = 'USER_TRIAL_REQUEST'
export const USER_TRIAL_SUCCESS = 'USER_TRIAL_SUCCESS'
export const USER_TRIAL_FAIL = 'USER_TRIAL_FAIL'

// export const USER_LOGOUT = 'USER_LOGOUT'
