const posts = [
	{
		_id: '1',
		title: 'Minecraftで英語を学ぼう',
		description: 'ゲームをしながら英会話を学ぶことができたらいかがですか?',
		author: 'Shinichiro Suzuki',
		price: 4000,
		rating: 4.5,
		gameName: 'Minecraft (マインクラフト)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
	{
		_id: '2',
		title: 'APEXで英語を学ぼう',
		description: 'FPSゲームをして色々遊ぶのは楽しいです',
		author: 'Rukami Dasiy',
		price: 7000,
		rating: 4.0,
		gameName: 'Apex Legends (エーペックスレジェンズ)',
		numReviews: 3,
	},
]

export default posts
